language: node_js

node_js:
  - "stable"
install:
  - npm install
script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  fqdn: vidar.cyris.moe
  local_dir: dist/
  on:
    branch: master